version: '2'
services:
  rabbit01:
    # build: ./
    image: silverbulleters/docker-rmq-cluster
    hostname: rabbit01
    environment:
      - RABBITMQ_ERLANG_COOKIE=E3r4l6a8n5g
      # - RABBITMQ_HIPE_COMPILE=1
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"
  # rabbit2:
  #   build: ./
  #   hostname: rabbit2
  #   depends_on: 
  #     - rabbit1
  #   environment:
  #     - ERLANG_COOKIE=abcdefg
  #     - CLUSTER_WITH=rabbit1
  #     - ENABLE_RAM=true
  #     - RABBITMQ_HIPE_COMPILE=1
  #   ports:
  #     - "5673:5672"
  # rabbit3:
  #   build: ./
  #   hostname: rabbit3
  #   depends_on: 
  #     - rabbit1
  #   environment:
  #     - ERLANG_COOKIE=abcdefg
  #     - CLUSTER_WITH=rabbit1
  #     - RABBITMQ_HIPE_COMPILE=1
  #   ports:
  #     - "5674:5672"
  # rabbit4:                         
  #   build: ./
  #   hostname: rabbit4              
  #   depends_on:                    
  #     - rabbit1                    
  #   environment:                   
  #     - ERLANG_COOKIE=abcdefg      
  #     - CLUSTER_WITH=rabbit1       
  #     - RABBITMQ_HIPE_COMPILE=1    
  #   ports:                         
  #     - "5675:5672"              
