version: '2'
services:
  rabbit1:
    image: rabbit-cluster
    hostname: rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: rabbit-cluster
    hostname: rabbit2
    depends_on: 
      - rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit1
      - ENABLE_RAM=true
    ports:
      - "5673:5672"
  rabbit3:
    image: rabbit-cluster
    hostname: rabbit3
    depends_on: 
      - rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit1
    ports:
      - "5674:5672"
