#!/bin/bash

hostname=`hostname`
RABBITMQ_NODENAME=${RABBITMQ_NODENAME:-rabbit}

if [ -z "$CLUSTER_WITH" ]; then
  echo "Running as single server"
  rabbitmq-server

  rabbitmqctl add_user $ADMIN $PASSWD

  rabbitmqctl set_user_tags $ADMIN administrator

  rabbitmqctl set_permissions -p / $ADMIN ".*" ".*" ".*"

else
  echo "Running as clustered server"
  /usr/sbin/rabbitmq-server -detached

  if [[ ! -z $(rabbitmqctl cluster_status | grep $CLUSTER_WITH) ]]; then
    echo Alerady joined;
  else
    rabbitmqctl stop_app
    echo "Joining cluster $CLUSTER_WITH"
    rabbitmqctl join_cluster ${ENABLE_RAM:+--ram} $RABBITMQ_NODENAME@$CLUSTER_WITH

    echo "Enable Mirror"
    # Mirror
    rabbitmqctl set_policy all '^.*' '{"ha-mode": "all"}' -p /

    rabbitmqctl start_app
  fi;
  # Tail to keep the a foreground process active..
  tail -f /var/log/rabbitmq/*
fi
